version = 1

exclude_patterns = [
  "makemigrations.py",
  "runtests.py",
  "tests/**",
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  max_line_length = 120
  runtime_version = "3.x.x"
